#!/usr/bin/env bash

usage() {
    echo "Usage: $0 --snap-name <snap-name> --buildinfo-url <buildinfo-url>"
    exit 1
}

# Take snap_name and buildinfo_url as parameters called --snap-name and --buildinfo-url
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --snap-name)
            snap_name="$2"
            shift 2
            ;;
        --buildinfo-url)
            buildinfo_url="$2"
            shift 2
            ;;
        --help)
            usage
            ;;
        *)
            shift
            ;;
    esac
done

# Check if required parameters are provided
if [ -z "$snap_name" ] || [ -z "$buildinfo_url" ]; then
    usage
fi

# Query the snap store for the latest version of the powershell-preview snap
latest_store_version=$(snap info "$snap_name" | grep -m1 "latest/edge:" | awk '{print $2}')
# Query the buildinfo URL for latest preview version
latest_buildinfo_version=$(curl --silent --location "$buildinfo_url" | jq --raw-output '.ReleaseTag' | sed 's/^v//')

# Compare the two versions
if dpkg --compare-versions "$latest_store_version" "lt" "$latest_buildinfo_version"; then
    echo "The latest version in the store ($latest_store_version) is older than the latest version in the buildinfo ($latest_buildinfo_version)"
    exit 0
else
    echo "The latest version in the store ($latest_store_version) is the same or newer than the latest version in the buildinfo ($latest_buildinfo_version)"
    exit 1
fi
