name: powershell-lts

on:
  push:
    branches: 
      - main
    paths:
      - 'powershell-lts/**'
  pull_request:
    branches: main
    paths:
      - 'powershell-lts/**'
  schedule:
    - cron: '0 0 * * 1-5'
  workflow_dispatch:

jobs:
  needs-store-publishing:
    uses: ./.github/workflows/template-scheduler-needs-publishing.yaml
    with:
      release: 'lts'
      enable-mattermost-notifications: ${{ github.event_name == 'schedule' }}
    secrets:
      MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
  build:
    uses: ./.github/workflows/template-build.yaml
    with:
      release: 'lts'
    needs: needs-store-publishing
    if: ${{ !(github.event_name == 'schedule' && needs.needs-store-publishing.outputs.needs-publishing == 'false') }}
  test:
    uses: ./.github/workflows/template-test.yaml
    needs: build
    with:
      release: 'lts'
  publish:
    uses: ./.github/workflows/template-publish.yaml
    needs: test
    if: ${{ contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name) && github.ref_name == 'main' }}
    with:
      release: 'lts'
    secrets:
      SNAP_STORE_TOKEN: ${{ secrets.SNAP_STORE_TOKEN }}
