name: powershell-lts-scheduler

on:
  schedule:
    - cron: '0 0 * * 1-5'
  workflow_dispatch:

jobs:
  needs-store-publishing:
    uses: ./.github/workflows/template-scheduler-needs-publishing.yaml
    with:
      release: 'lts'
    secrets:
      MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
  build:
    uses: ./.github/workflows/template-build.yaml
    needs: needs-store-publishing
    if: ${{ needs.needs-store-publishing.outputs.needs-publishing == 'true' }}
    with:
      release: 'lts'
  test:
    uses: ./.github/workflows/template-test.yaml
    needs: build
    with:
      release: 'lts'
  publish:
    uses: ./.github/workflows/template-publish.yaml
    needs: test
    with:
      release: 'lts'
    secrets:
      SNAP_STORE_TOKEN: ${{ secrets.SNAP_STORE_TOKEN }}
