name: powershell-lts

on:
  push:
    branches: main
    paths:
      - 'powershell-lts/**'
  pull_request:
    branches: main
    paths:
      - 'powershell-lts/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/template-build.yaml
    with:
      release: 'lts'
  publish:
    uses: ./.github/workflows/template-publish.yaml
    needs: build
    # if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) && github.ref_name == 'main' }}
    if: false
    with:
      release: 'lts'
