name: Test PowerShell Snaps

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.generate-matrix.outputs.artifacts }}
      architectures: ${{ steps.generate-matrix.outputs.architectures }}
    steps:
      - name: Generate Dynamic Artifacts Matrix
        id: generate-matrix
        shell: bash
        run: |
          # Array of enabled architecture for the PowerShell snaps
          ARCHITECTURES="amd64"

          # First gsub: removes leading and trailing whitespaces
          # Second gsub: replaces any number of subsequent whitespaces with only one whitespace
          ARCHITECTURES_ARRAY=$(echo "$ARCHITECTURES" | jq --raw-input --compact-output \
            'gsub("^\\s+|\\s+$"; "") | gsub("\\s+"; " ") | split(" ")')

          echo "architectures=$ARCHITECTURES_ARRAY" >> $GITHUB_OUTPUT

  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ${{ fromJson(needs.generate-matrix.outputs.architectures) }}
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - name: Print matrix
        shell: bash
        run: |
          echo "Architectures: ${{ matrix.architecture }}"
      - name: Test PowerShell Snaps
        id: test
        uses: ./.github/actions/test-powershell-snap
        with:
          release: ${{ inputs.release }}
          architecture: ${{ matrix.architecture }}
