name: Build PowerShell Snap

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  build-powershell-snap:
    strategy:
      matrix:
        os:
          - [self-hosted, large, noble, x64]
          - [self-hosted, large, noble, arm64]
          - [self-hosted, large, noble, s390x]
          - [self-hosted, large, noble, ppc64el]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      id: checkout
    - name: Build PowerShell Snap
      uses: ./.github/actions/build-powershell-snap
      with:
        release: ${{ inputs.release }}
