name: Build PowerShell Snap

on:
  workflow_call:
    outputs:
      architectures:
        description: "The architectures matrix to build/test/publish the snaps against"
        value: ${{ jobs.generate-matrix.outputs.architectures }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.generate-matrix.outputs.architectures }}
    steps:
      - name: Generate Dynamic Artifacts Matrix
        id: generate-matrix
        shell: bash
        run: |
          # Array of enabled architecture for the PowerShell snaps
          ARCHITECTURES="amd64"

          # First gsub: removes leading and trailing whitespaces
          # Second gsub: replaces any number of subsequent whitespaces with only one whitespace
          ARCHITECTURES_ARRAY=$(echo "$ARCHITECTURES" | jq --raw-input --compact-output \
            'gsub("^\\s+|\\s+$"; "") | gsub("\\s+"; " ") | split(" ")')

          echo "architectures=$ARCHITECTURES_ARRAY" >> $GITHUB_OUTPUT
