name: Test PowerShell Snaps

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - [self-hosted, large, jammy, X64]
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - name: Test PowerShell Snaps
        id: test
        uses: ./.github/actions/test-powershell-snap
        with:
          release: ${{ inputs.release }}
