name: Test PowerShell Snaps

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  test:
    strategy:
      matrix:
        os:
          - [self-hosted, linux, large, noble, x64]
          - [self-hosted, linux, large, noble, arm64]
          - [self-hosted, linux, noble, s390x]
          - [self-hosted, linux, noble, ppc64el]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      id: checkout
    - name: Test PowerShell Snaps
      id: test
      uses: ./.github/actions/test-powershell-snap
      with:
        release: ${{ inputs.release }}
